name: LD2410Async Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:   # allows manual triggering from the GitHub Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        board:
          - fqbn: "esp32:esp32:esp32"
            platform-name: esp32:esp32

  # Make board type-specific customizations to the matrix jobs
        include:
          - board:
              platform-name: esp32:esp32
            platforms: |
              # Install ESP32 platform via Boards Manager
              - name: esp32:esp32
                source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json


    steps:
      # Checkout repo
      - name: Checkout
        uses: actions/checkout@v3



      - name: Cache Arduino platform
        uses: actions/cache@v3
        with:
          path: ~/.arduino15
          key: arduino-${{ matrix.board.platform-name }}

      - name: Install ESP32 platform dependencies
        if: matrix.board.platform-name == 'esp32:esp32'
        run: pip3 install pyserial

      - name: Compile examples
        uses: arduino/compile-sketches@v1
        with:
          platforms: ${{ matrix.platforms }}
          fqbn: ${{ matrix.board.fqbn }}
          libraries: |
            - name: ESP Async TCP
            - name: ESP Async WebServer
            - source-path: .
          enable-deltas-report: false
          sketch-paths: |
            - examples
          enable-warnings-report: 'true'

