name: LD2410Async Doxygen Docs

on:
  push:
    branches:
      - master
      - '**'   # all feature branches
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

      - name: Generate Documentation
        run: |
          mkdir -p docu
          doxygen Doxyfile

      - name: Commit & Push documentation
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Stage only docu folder
          git add docu

          # Skip commit if nothing changed
          if git diff --cached --quiet; then
            echo "Documentation is already up to date. No commit needed."
            exit 0
          fi

          git commit -m "Update Doxygen documentation"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
